from typing import Protocol

from app.curriculum.domain.models import LessonNode, LessonNodeStatus, LessonPlan


class LessonPlanRepository(Protocol):
    async def save(self, plan: LessonPlan) -> None: ...

    async def save_nodes(self, nodes: list[LessonNode]) -> None: ...

    async def replace_nodes(self, lesson_plan_id: str, nodes: list[LessonNode]) -> None: ...

    async def get(self, plan_id: str) -> LessonPlan | None: ...

    async def get_node(self, node_id: str) -> LessonNode | None: ...

    async def update_node_status(self, node_id: str, status: LessonNodeStatus) -> None: ...

    async def unlock_next_node(self, lesson_plan_id: str, completed_sequence_index: int) -> None: ...

    async def list_for_session(self, session_id: str) -> list[LessonPlan]: ...
