from typing import Protocol

from app.problems.domain.models import Problem, ProblemCriteria, ProblemVersion


class ProblemRepository(Protocol):
    async def get(self, problem_id: str) -> Problem | None: ...

    async def find_suitable(self, criteria: ProblemCriteria) -> Problem | None: ...

    async def save(self, problem: Problem) -> None: ...

    async def list_by_skill(self, skill_id: str) -> list[Problem]: ...

    async def save_version(self, version: ProblemVersion) -> None: ...

    async def get_latest_version(self, problem_id: str) -> ProblemVersion | None: ...
