PROBLEM_SYSTEM_PROMPT = (
    "You write a single DSA practice problem for a given skill, language, and difficulty. "
    "Produce a clear statement (markdown), a correct reference solution, and 2-4 worked "
    "examples.\n\n"
    "CRITICAL — execution model: both `boilerplate` and `reference_solution` are run as a "
    "plain, standalone program. There is NO test harness, NO class instantiation, and NO "
    "function call injected around your code — nothing else invokes it. Each one must, by "
    "itself, read the test case's input from stdin and print the final answer to stdout "
    "(e.g. Python: input()/print(); Java: a real `public static void main` using Scanner "
    "and System.out; C++: cin/cout; JavaScript: reading process.stdin and console.log). "
    "Never emit a bare class or function definition with no entry point — code that only "
    "defines a method and never calls or prints anything produces no output at all and "
    "will be marked wrong, even if the logic inside it is correct.\n\n"
    "`boilerplate` must already contain this exact input-reading and output-printing "
    "driver, fully wired up and working, with ONLY the core algorithm left as a stub "
    "(e.g. `pass` / a TODO) for the learner to fill in — so running the boilerplate "
    "completely unmodified executes end-to-end and simply produces a wrong-but-non-empty "
    "answer, never silence. `reference_solution` is the same program with the stub "
    "correctly implemented — it must actually solve the stated problem, since it will be "
    "executed for real against each example's input and its exact stdout becomes the "
    "graded expected output. Double-check it prints something for every example, in "
    "exactly the input format you wrote for that example.\n\n"
    "Also produce: a short constraints section (input value ranges, expected time/space "
    "complexity); 1-3 progressive hints ordered from a gentle nudge to a stronger hint, "
    "never revealing the full solution; and 2-4 short topical tags (e.g. 'two-pointers', "
    "'hash-map')."
)


def problem_user_prompt(skill: str, language: str, difficulty: str) -> str:
    return f"Skill: {skill}\nLanguage: {language}\nDifficulty: {difficulty}"
